### ISSUE TITLE
addWord 是不是只能动态添加词组？

### ISSUE THREAD

**Issue by xkungfu** [binaryoung/jieba-php#1]
不错的代码，感谢分享！
调用addWord 时发现只对当前执行的代码生效，并没有存入dict.txt文件。
请问针对dict.txt中的词组进行增删改查等操作，是不是在rs源码中也不存在，需要自己另外编写代码实现？

**Comment by binaryoung** [comment]
对的，`addWord`函数只会对当前实例生效。对`dict.txt`中的词组进行增删改查可以使用`useDictionary`函数载入自定义词典文件，先复制一份`dict.txt`到自定义位置修改，再使用此函数载入字典。具体事例可以参考[example.php](https://github.com/binaryoung/jieba-php/blob/v0.1.0/examples/example.php#L61-L68)。

**Comment by xkungfu** [comment]
好的，明白了，谢谢！
